Converts map object to list (Python 3 compatibility)
mathebox/django_hana_pyhdb pull request #17
Opened 2017-02-10 18:12 UTC by amarvin

2017-02-10 19:36 UTC, mathebox requested changes
It would be great if you could also provide a test which checks this line. This can be a general case or the query that's similar to your. Have a look at [`tests/test_queries.py`](https://github.com/mathebox/django_hana_pyhdb/blob/fe52f8f05781d08293d18200c418bc1a07c3eb4b/tests/test_queries.py)

2017-02-10 19:36 UTC, mathebox commented on django_hana/operations.py
> +                insert_param_groups.append(list(map(self.sanitize_bool, p)))
I would prefer a list comprehension:
```
[self.sanitize_bool(value) for value in p]
```

2017-02-14 17:10 UTC, amarvin commented
I converted it to list comprehension, but haven't added a test yet. I'm quite new to this.

2017-02-14 18:17 UTC, amarvin commented
I took a couple cracks at writing a test, but failed, sorry!

2017-02-14 21:38 UTC, amarvin commented
What was I doing wrong in my test? I get a strange database connection error in Travis-CI on the .save().

2017-02-14 22:23 UTC, mathebox commented
On travis the test tries to connect to a SAP HANA instance. This is not possible.
Creating a mock for `BaseDatabaseSchemaEditor.execute` is necessary when testing methods that alter the schema of the table (e.g. migration). An `INSERT` query will need a different mock.
I will look into this.

2017-02-15 13:27 UTC, amarvin commented
I tried modifying the test with a mock of the .save command, as you mentioned, using this as an example: https://stackoverflow.com/questions/10545049/mocking-django-model-and-save. I was unsuccessful, sorry.

2017-02-15 17:58 UTC, mathebox commented
This should fixed by 47f029e75140ffba0504d5a85c6f3fe55d36b52b. I have also improved the mock behavior of the tests. This should make the tests better understandable. Have a look.
If you have further questions or bugs, please create an issue.

2017-02-15 17:58 UTC, closed without merging

2017-02-15 18:00 UTC, amarvin commented
Terrific, thanks!