Add Django 1.9 and 1.10 compatability
mathebox/django_hana_pyhdb pull request #2
Opened 2016-11-28 13:10 UTC by cmfcmf

This should fix #1.

2016-11-29 11:51 UTC, cmfcmf commented
Although #1 is fixed, it appears like there are additional issues with Django 1.10. The migrations currently seem unable to create tables. I will investigate further.

2016-11-30 08:22 UTC, mathebox requested changes
Thanks a lot for your PR. I would be great if you could fix the remaining issues with django 1.10

2016-11-30 08:22 UTC, mathebox commented on django_hana/compiler.py
> +import django
Please move this to line 3.

2016-11-30 08:22 UTC, mathebox commented on django_hana/compiler.py
> +    def __createPlaceholder(self, field, val):
Can you create a `compat.py` similar to the approach of django rest framework? https://github.com/tomchristie/django-rest-framework/blob/master/CONTRIBUTING.md#managing-compatibility-issues

2016-11-30 08:22 UTC, mathebox commented on django_hana/compiler.py
> +        if StrictVersion(django.get_version()) >= StrictVersion('1.9.0'):
I would prefer `django.VERSION >= (1, 9)`. Have a look at `compat.py` of DRF ;)

2016-12-01 13:57 UTC, cmfcmf commented
I've now fixed a few more issues. Migrations now run with Django 1.8, 1.9 and 1.10. I also incorporated a `compat.py` file. Please take a look @mathebox!

2016-12-08 10:13 UTC, cmfcmf commented
Hey @mathebox, anything left I need to do before this can be merged?

2016-12-08 20:02 UTC, mathebox approved these changes

2016-12-08 20:02 UTC, mathebox commented
Sorry, busy week..

LGTM

2016-12-08 20:03 UTC, merged

2016-12-08 20:29 UTC, cmfcmf commented
Thanks Max!